source/YAAS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^populate/$', views.populate_db, name='populate'),
    url(r'^admin/', admin.site.urls),
    url(r'^auctions/', include('auctions.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/api/urls.py
from django.conf.urls import url
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'api'

urlpatterns = [
    url(r'^auctions/$', views.AuctionsList.as_view()),
    url(r'^auctions/(?P<auction_id>[0-9]+)/$', views.AuctionDetails.as_view()),
    url(r'^auctions/(?P<auction_id>[0-9]+)/bid/$', csrf_exempt(views.BidOnAuction.as_view())),
]

source/auctions/urls.py
from django.conf.urls import url
from . import views

app_name = 'auctions'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^myauctions/$', views.my_auctions, name='myauctions'),
    url(r'^browse/$', views.browse, name='browse'),
    url(r'^banned/$', views.browse_banned, name='banned'),
    url(r'^(?P<auction_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^auction/add/$', views.create_auction, name='auction-add'),
    url(r'^auction/confirm/$', views.confirm_auction, name='auction-confirm'),
    url(r'^auction/(?P<pk>[0-9]+)/edit/$', views.AuctionEditFormView.as_view(), name='auction-update'),
    url(r'^language/$', views.change_language, name='language'),
    url(r'^auction/(?P<pk>[0-9]+)/ban/$', views.auction_ban, name='auction-ban'),
    url(r'^auction/(?P<pk>[0-9]+)/unban/$', views.auction_unban, name='auction-unban'),
    url(r'^auction/(?P<auction_id>[0-9]+)/bid/$', views.BidFormFormView.as_view() , name='bid'),
    url(r'^auction/non/edit/(?P<edit_token>[\w\-]+)/$', views.AuctionEditFormNonView.as_view(), name='auction-edit-without'),
]

source/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^editprofile/$', views.UserEditFormView.as_view(), name='editprofile'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
]

source/auctions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator


# Model for saving user language preference
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    language = models.CharField(max_length=10, default='en')


# Model for saving currency values from api
class Currency(models.Model):
    currency = models.CharField(max_length=10)
    value = models.DecimalField(max_digits=19, decimal_places=4)


# Model for saving auction data
class Auction(models.Model):
    STATUS__CHOICES = (
        ('Active', 'Active'),
        ('Banned', 'Banned'),
        ('Due', 'Due'),
        ('Adjudicated', 'Adjudicated'),
    )
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    description = models.CharField(max_length=4000)
    currency = models.CharField(max_length=10)
    edit_token = models.CharField(max_length=500)
    starting_price = models.DecimalField(max_length=30, max_digits=19, decimal_places=2)
    bid_price = models.DecimalField(max_length=30, max_digits=19, decimal_places=2, null=True)
    winner_id = models.IntegerField(null=True)
    start_date = models.DateTimeField(blank=True)
    duration_hours = models.IntegerField(default=72, validators=[MinValueValidator(72)])
    end_date = models.DateTimeField(blank=True)
    status = models.CharField(max_length=15, choices=STATUS__CHOICES, default='Active')
    revision = models.IntegerField(default=1)

    def __str__(self):
        return self.title


# Model for saving bid data
class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    bid_amount = models.DecimalField(max_length=30, max_digits=19, decimal_places=2)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)

    def __str__(self):
        return self.bidder.username

source/auctions/forms.py
from django import forms
from .models import Auction, Bid


class AuctionForm(forms.ModelForm):

    class Meta:
        model = Auction
        fields = ['title', 'description', 'starting_price', 'duration_hours']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
        }

class EditAuctionForm(forms.ModelForm):

    class Meta:
        model = Auction
        fields = ['description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
        }

class BidForm(forms.ModelForm):

    class Meta:
        model = Bid
        fields = ['bid_amount']

source/auctions/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.views.generic import View
from .models import Auction, Bid, Profile, Currency
from .forms import AuctionForm, EditAuctionForm, BidForm
from django.utils import timezone
from datetime import datetime, timedelta
from django.utils.crypto import get_random_string
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
import threading
import requests
from decimal import Decimal
import time


# Options for currency selection in template and returned from api
currency_options = [{'name':'Australian Dollar','value':'AUD'},
{'name':'Euros','value':'EUR'},
{'name':'Bulgarian Lev','value':'BGN'},
{'name':'Brazilian Real','value':'BRL'},
{'name':'Canadian Dollar','value':'CAD'},
{'name':'Swiss Franc','value':'CHF'},
{'name':'Renminbi(Yuan)','value':'CNY'},
{'name':'Czech Koruna','value':'CZK'},
{'name':'Danish Krone','value':'DKK'},
{'name':'Pound Sterling','value':'GBP'},
{'name':'HK Dollar','value':'HKD'},
{'name':'Croatian Kuna','value':'HRK'},
{'name':'Forint','value':'HUF'},
{'name':'Rupiah','value':'IDR'},
{'name':'Israeli Sheqel','value':'ILS'},
{'name':'Indian Rupee','value':'INR'},
{'name':'Yen','value':'JPY'},
{'name':'Won','value':'KRW'},
{'name':'Mexican Peso','value':'MXN'},
{'name':'Malaysian Ringgit','value':'MYR'},
{'name':'Norwegian Krone','value':'NOK'},
{'name':'NZ Dollar','value':'NZD'},
{'name':'Philippine Peso','value':'PHP'},
{'name':'Zloty','value':'PLN'},
{'name':'Russian Ruble','value':'RUB'},
{'name':'Swedish Krona','value':'SEK'},
{'name':'Singapore Dollar','value':'SGD'},
{'name':'Thai Baht','value':'THB'},
{'name':'Turk Lira','value':'TRY'},
{'name':'US Dollar','value':'USD'},
{'name':'Rand','value':'ZAR'}]


# Get currency value prices from database
def currency_exchange(currency):
    currency_val = 1.0000
    if currency != 'EUR':
        if Currency.objects.filter(currency=currency).exists():
            curr = Currency.objects.get(currency=currency)
            currency_val = float(curr.value)
    return currency_val


# Change language for user and save preference in database if user is authenticated
@csrf_exempt
def change_language(request):
    query = request.POST.get("lang")
    if (query == ''):
        return redirect('auctions:index')
    if (query == 'en' or query == 'sv' or query == 'fi'):
        request.session['language'] = query
        if request.user.is_authenticated():
            user = User.objects.get(pk=request.user.id)
            profile = Profile.objects.get(user=user)
            profile.language = query
            profile.save()
    return redirect('auctions:index')


# Folder selection based on language
def language_folder_selection(request):
    language = ''
    if 'language' in request.session:
        language = request.session['language']
    if language == 'fi':
        language = 'fi/'
    if language == 'sv':
        language = 'sv/'
    if language == 'en':
        language = ''
    return language


# Decide header based on user authentication
def get_base_template(request):
    if request.user.is_authenticated():
        base_template = "auctions/base.html"
    else:
        base_template = "auctions/base_visitor.html"
    return base_template


# Browse 10 latest auctions or searched auctions
def index(request):
    base_template = get_base_template(request)
    query = request.GET.get("q")
    if query:
        auctions = Auction.objects.filter(title__icontains=query, status='Active').distinct().order_by('-id')
        return render(request, 'auctions/'+language_folder_selection(request)+'index.html', {'object_list': auctions, 'heading': "Searched Auctions", 'base_template': base_template})
    else:
        auctions = Auction.objects.filter(status='Active').order_by('-id')[:10]
        return render(request, 'auctions/'+language_folder_selection(request)+'index.html', {'object_list': auctions, 'heading': "Latest Auctions", 'base_template': base_template})


# Browse all auctions
def browse(request):
    base_template = get_base_template(request)
    auctions = Auction.objects.filter(status='Active').order_by('-id')
    return render(request,  'auctions/'+language_folder_selection(request)+'index.html', {'object_list': auctions, 'heading': "Auctions", 'base_template': base_template})


# Browse banned auctions - admin(super) user only
def browse_banned(request):
    if not request.user.is_superuser:
        return HttpResponse('You are not authorized to perform this action')
    base_template = get_base_template(request)
    auctions = Auction.objects.filter(status='Banned').order_by('-id')
    return render(request, 'auctions/'+language_folder_selection(request)+'index.html', {'object_list': auctions, 'heading': "Banned Auctions", 'base_template': base_template})


# Browse auctions listed by user
@login_required(login_url='users:login')
def my_auctions(request):
    base_template = get_base_template(request)
    auctions = Auction.objects.filter(seller_id=request.user.pk, status='Active').order_by('-id')[:10]
    return render(request, 'auctions/'+language_folder_selection(request)+'index.html', {'object_list': auctions, 'heading': "My Auctions", 'base_template': base_template})


# Details of an auction
def detail(request, auction_id):
    query = request.GET.get("curr")
    currency = 'EUR'
    if query:
        currency = query
        request.session['project'] = currency
    else:
        if 'project' in request.session:
            currency = request.session['project']
    currency_val = currency_exchange(currency)
    auction = get_object_or_404(Auction, pk=auction_id, status='Active')
    auction.bid_set.all()
    diff = auction.end_date - timezone.now()
    seconds = diff.total_seconds()
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    context = {
        'auction': auction,
        'hours': hours,
        'minutes': minutes,
        'base_template': get_base_template(request),
        'currency_options': currency_options,
        'currency': currency,
        'currency_val': currency_val}
    return render(request, 'auctions/'+language_folder_selection(request)+'details.html', context)


# Get data from forum and save in session storage, then redirect to confirmation page
@login_required(login_url='users:login')
def create_auction(request):
        form = AuctionForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            context = {
                "form": form,
                'base_template': "auctions/base.html",
            }
            auction = form.save(commit=False)
            save_into_session(request, auction)
            return render(request, 'auctions/'+language_folder_selection(request)+'auction_confirmation_form.html', context)
        context = {
           "form": form,
            'base_template': "auctions/base.html",
        }
        return render(request, 'auctions/'+language_folder_selection(request)+'auction_form.html', context)


# On user confirmation get data from session storage and save in database
@login_required(login_url='users:login')
def confirm_auction(request):
        if request.method == 'POST':
            if (request.POST['confirm'] == 'True'):
                auction = get_from_session(request)
                auction.seller = request.user
                auction.start_date = timezone.now()
                auction.end_date = auction.start_date + timedelta(hours=auction.duration_hours)
                auction.edit_token =  auction.start_date.strftime('%Y%m%d%H%M%S') + get_random_string()
                auction.revision = 1
                auction.save()
                subject = 'Auction is created'
                body = 'It is to inform that Auction with title "' + auction.title + '" has been created on YAAS'
                body += '\nyou can see the description of created auction by following link '
                body += '\n' + request.get_host() + '/auctions/' + str(auction.id) + '/'
                body += '\nyou can edit description of auction by using following link '
                body += '\n' + request.get_host() + '/auctions/auction/non/edit/'+ auction.edit_token + '/'
                email = EmailMessage(subject, body, from_email='no-reply@yaas.com', to=['user@yaas.com'])
                email.send()
                return redirect('auctions:index')
        return redirect('auctions:index')


# Edit auction description without signing in
class AuctionEditFormNonView(View):
    form_class = EditAuctionForm
    def get(self, request, edit_token):
        template_name = 'auctions/' + language_folder_selection(request) + 'auction_form.html'
        form = self.form_class(None)
        num_results = Auction.objects.filter(edit_token=edit_token).count()
        if num_results > 0:
            auction = Auction.objects.get(edit_token=edit_token)
            form.fields['description'].initial = auction.description
            return render(request, template_name, {'form': form, 'base_template': get_base_template(request)})
        return redirect('auctions:index')
    def post(self, request, edit_token):
        template_name = 'auctions/' + language_folder_selection(request) + 'auction_form.html'
        form = self.form_class(request.POST)
        if form.is_valid():
            db_auction = Auction.objects.get(edit_token=edit_token)
            db_auction.description = form.cleaned_data['description']
            db_auction.revision = db_auction.revision + 1
            db_auction.save()
            return redirect('auctions:index')
        return render(request, template_name, {'form': form, 'base_template': get_base_template(request)})


# Edit auction description with authenticated user

source/auctions/templates/auctions/auction_form.html
{% extends base_template %}
{% block title %}Add Auction{% endblock %}
{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'auctions/form-template.html' %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

source/auctions/templates/auctions/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}YASS{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'auctions/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand active" href="{% url 'auctions:index' %}">YAAS</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'auctions:index' %}"><span class="glyphicon glyphicon-flash" aria-hidden="true"></span>&nbsp; Latest</a></li>
                <li class="active"><a href="{% url 'auctions:browse' %}"><span class="glyphicon glyphicon-flash" aria-hidden="true"></span>Browse</a></li>
                {% if user.is_superuser %}
                <li class="active"><a href="{% url 'auctions:banned' %}"><span class="glyphicon glyphicon-screenshot" aria-hidden="true"></span>&nbsp; Banned</a></li>
                {% endif %}
            </ul>
            <form style="padding: 0px 4px;" class="navbar-form navbar-left" role="search" method="get" action="{% url 'auctions:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <form style="padding: 0px 4px;" class="navbar-form navbar-left" role="lang" method="post" action="{% url 'auctions:language' %}">
                {% csrf_token %}
                <div class="form-group">
                    <select class="form-control" name="lang">
                        <option value="" >Language</option>
                        <option value="en" >English</option>
                        <option value="fi" >Finnish</option>
                        <option value="sv" >Swedish</option>
                    </select>
                    <button type="submit" class="btn btn-default">Submit</button>
                 </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="{% url 'auctions:myauctions' %}">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&nbsp; My Auctions
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'users:editprofile' %}">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&nbsp; Edit Profile
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'auctions:auction-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Auction
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'users:logout'%}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

source/auctions/templates/auctions/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}YASS{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'auctions/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand active" href="{% url 'auctions:index' %}">YAAS</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'auctions:index' %}"><span class="glyphicon glyphicon-flash" aria-hidden="true"></span>&nbsp; Latest</a></li>
                <li class="active"><a href="{% url 'auctions:browse' %}"><span class="glyphicon glyphicon-flash" aria-hidden="true"></span>Browse</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'auctions:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <form class="navbar-form navbar-left" role="lang" method="post" action="{% url 'auctions:language' %}">
                {% csrf_token %}
                <div class="form-group">
                    <select class="form-control" name="lang">
                        <option value="" >Language</option>
                        <option value="en" >English</option>
                        <option value="fi" >Finnish</option>
                        <option value="sv" >Swedish</option>
                    </select>
                    <button type="submit" class="btn btn-default">Submit</button>
                 </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="{% url 'auctions:auction-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Auction
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'users:register'%}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Register
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'users:login'%}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

source/auctions/templates/auctions/details.html
{% extends base_template %}
{% block title %}Details{% endblock %}

{% block body %}
{% load staticfiles %}
{% load app_filters %}
    <script>
        hourd = {{ hours }};
        minuted = {{ minutes }} + 1;
    window.setInterval(function() {
        var elem = document.getElementById("end");
        if (minuted == 0)
        {
            if (hourd !=0 ) {
                hourd = hourd - 1;
                minuted = 59;
               elem.innerHTML = hourd + ' H ' + minuted + ' M';
            }
            else
                elem.innerHTML = "Ended";
        }
        else{
            minuted = minuted - 1;
            elem.innerHTML = hourd + ' H ' + minuted + ' M';
            }

        }, 60000);
    </script>
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Auction Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="javascript:;">
                            <img src="{%  static 'auctions/images/auction_logo.jpg' %}" class="img-responsive">
                    </a>
                    <h1 data-toggle="tooltip" title="{{ auction.title }}" style="overflow: hidden">{{ auction.title}} <small>{{ auction.status }}</small></h1>
                    <h5 data-toggle="tooltip" title="End Date" style="overflow: hidden">End Date(UTC): {{ auction.end_date }}</h5>
                </div>
            </div>
        </div>

        <!-- Right Auction Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="javascript:;">Currency</a></li>
                <li>

                    <form name="form" onChange="form.submit();" class="form" role="curr" method="get" action="">
                    <div class="form-group">
                    <select class="form-control" name="curr">
                            {% for option in currency_options %}
                                <option value="{{ option.value }}" {% if option.value == currency %}selected{% endif %}>{{ option.name }}</option>
                            {% endfor %}
                    </select>
                    </div>
                    </form>
                </li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Auction Details</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Current Price</th>
                            <th>Ending in</th>
                            <th>Bidders Count</th>
                            <th>Highest Bidder</th>
                            <th>Seller</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                {% if auction.bid_price %}
                                <td>{{ auction.bid_price|multiply:currency_val }} <strong>{{ currency }}</strong></td>
                                {% else %}
                                <td>{{ auction.starting_price|multiply:currency_val }} <strong>{{ currency }}</strong></td>
                                {% endif %}
                                <td id="end">{{ hours }} H {{ minutes }} M</td>
                                <td>{{ auction.bid_set.all.count }}</td>
                                <td>
                                    {% if auction.bid_set.all.count > 0 %}
                                    {% for data in auction.bid_set.all %}
                                        {% if data.bidder.pk == auction.winner_id %}
                                            {% if user.id != auction.winner_id %}
                                                {{ data.bidder }}
                                            {% else %}
                                                YOU
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                    {% else %}
                                        No bidder
                                    {% endif %}
                                </td>
                                <td>
                                    {{ auction.seller.username }}
                                </td>
                                <td>
                                    {% if user.id != auction.seller.id %}
                                    {% if user.id != auction.winner_id %}
                                    <a href="{% url 'auctions:bid' auction.id %}">
                                        <button  class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Bid
                                        </button>
                                    </a>
                                    {% else %}
                                        {% if user.is_authenticated %}
                                        <button  class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; You are highest bidder
                                        </button>
                                        {% endif %}
                                    {% endif %}
                                    {% else %}
                                        <button  class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Seller Can't Bid
                                        </button>
                                    {% endif %}
                                    {% if user.is_superuser %}
                                    <a href="{% url 'auctions:auction-ban' auction.id %}">
                                        <button  class="btn btn-dark btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Ban
                                        </button>

                                    </a>
                                    {% endif %}
                                    {% if user.id == auction.seller.id %}
                                    <a href="{% url 'auctions:auction-update' auction.id %}">
                                        <button  class="btn btn-dark btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Edit
                                        </button>

                                    </a>
                                    {% endif %}
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <h4>Title</h4>
                    {{ auction.title }}

                    <h4>Description</h4>
                    {{ auction.description }}

                    <h4>All Bidders</h4>
                    {% for data in auction.bid_set.all %}
                         {{ data.bidder }}<br />
                    {% endfor %}
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}